CREATE TABLE [dbo].[tblClientes]
(
	[IdCliente] INT NOT NULL PRIMARY KEY identity(1,1), 
	[IdStatus] INT NULL,
	[IdNegocio] INT NOT NULL, 
	[IdLocalidadNegocio] INT NOT NULL, 
	[Activo] bit default(1) not null,
	[AnuladoPor] VARCHAR(100) NULL, 
	[Apodo] varchar(100),
	[Apellidos] VARCHAR(100) NOT NULL,
	Codigo varchar(40) default NEWID(),
	[IdEstadoCivil] int not null,
	[FechaNacimiento] DateTime not null,
	[FechaModificado] DATETIME NULL, 
	[FechaInsertado] DateTime not null default getdate(), 
	[FechaAnulado] DATETIME NULL, 
	[IdTipoIdentificacion] INT NOT NULL, 
	[IdTipoProfesionUOcupacion] INT NOT NULL, 
	[InfoConyuge] VARCHAR(max),
	[InfoLaboral] VARCHAR(max),
	[InfoDireccion] VARCHAR(max),
	[InsertadoPor] varchar(100) not null,
	[ModificadoPor] VARCHAR(100) NULL, 
	[NoIdentificacion] varchar(20),
	[Nombres] VARCHAR(100) NOT NULL,
	[IdSexo] int not null,
	[TelefonoCasa] VARCHAR(20) NOT NULL,
	[TelefonoMovil] VARCHAR(20) NOT NULL,
    [CorreoElectronico] VARCHAR(30) NOT NULL, 
	[TieneConyuge] bit default 0,
	Imagen1FileName varchar(50),
	Imagen2FileName varchar(50),
	Imagenes varchar(max),
	[InfoReferencias] VARCHAR(max),
    --CONSTRAINT [FK_tblCliente_ToTblNegocios] FOREIGN KEY (IdNegocio) REFERENCES tblNegocios([IdNegocio]),
	CONSTRAINT [FK_tblCliente_ToTblLocalidadNegocios] FOREIGN KEY (IdLocalidadNegocio) REFERENCES tblLocalidadesNegocio([IdLocalidadNegocio]),
	CONSTRAINT [FK_tblCliente_UQ_IdentificationNumber] Unique NonClustered (idNegocio, IdTipoIdentificacion,NoIdentificacion),
	CONSTRAINT [FK_tblCliente_UQ_Codigo] Unique NonClustered(IdLocalidadNegocio, Codigo),
	CONSTRAINT [CK_NombresClientes_not_empty_string] CHECK  ((Nombres<>N''))
)
	
