CREATE TABLE [dbo].[tblGarantias]
(
	[IdGarantia] INT NOT NULL PRIMARY KEY  identity(1,1), 
    [IdClasificacion] INT NOT NULL, 
    [IdTipoGarantia] INT not NULL, 
    [IdModelo] INT NULL,
	IdMarca INT NULL,
    [NoIdentificacion] NVARCHAR(50) NOT NULL, 
    [IdNegocio] INT NOT NULL,
    	[IdLocalidadNegocio] INT NULL, 
    [Detalles] VARCHAR(4000) NULL,
	[Imagen1FileName] varchar(50),
	[Imagen2FileName] varchar(50),
	[Imagen3FileName] varchar(50),
	[Imagen4FileName] varchar(50),
	[InsertadoPor] varchar(100) not null,
	[FechaInsertado] DateTime not null default getdate(), 
    [ModificadoPor] VARCHAR(100) NULL, 
    [FechaModificado] DATETIME NULL, 
    [AnuladoPor] VARCHAR(100) NULL, 
    [FechaAnulado] DATETIME NULL,
    constraint fk_GarantiaMarca foreign KEY (IdMarca) REFERENCES tblMarcas(IdMarca),
    constraint fk_GarantiaModelo foreign KEY (IdModelo) REFERENCES tblModelos(IdModelo),
    constraint fk_GarantiaTiposGarantia foreign KEY (IdTipoGarantia) REFERENCES tblTiposGarantia(IdTipoGarantia),
    
)
