CREATE TABLE [core].[tblUsuarios] (
    [Id]                                   INT           NOT NULL,
    [IdLocalidadNegocio]                   INT           NOT NULL,
    [IdPersonal]                           INT           NULL,
    [LoginName]                            VARCHAR (50)  NOT NULL,
    [Password]                             VARCHAR (50)  NOT NULL,
    [Activo]                               BIT           NULL,
    [CorreoElectronico]                    VARCHAR (50)  NULL,
    [Telefono1]                            VARCHAR (50)  NULL,
    [Telefono2]                            VARCHAR (50)  NULL,
    [Bloqueado]                            BIT           NULL,
    [DebeCambiarContraseñaAlIniciarSesion] BIT           NULL,
    [EsEmpleado]                           BIT           NULL,
    [VigenteDesde]                         DATETIME      NULL,
    [VigenteHasta]                         DATETIME      NULL,
    [InicioVigenciaPassword]               DATETIME      NULL,
    [PasswordExpiraCadaXMes]               INT           NULL,
    [ImgFilePath]                          VARCHAR (MAX) NULL,
    [RazonBloqueo]                         INT           NULL,
    [InsertadoPor]                         VARCHAR (100) NOT NULL,
    [FechaInsertado]                       DATETIME      NOT NULL,
    [ModificadoPor]                        VARCHAR (100) NULL,
    [FechaModificado]                      DATETIME      NULL,
    [BorradoPor]                           VARCHAR (100) NULL,
    [FechaBorrado]                         DATETIME      NULL,
    CONSTRAINT [PK_tblUsuarios] PRIMARY KEY CLUSTERED ([Id] ASC)
);

